---
- name: Install recommended package (to use AUFS storage drivers)
  apt:
    pkg: linux-image-extra-virtual
    update_cache: yes
    install_recommends: no
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install packages necessary for APT to use a repository over HTTPS
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
    install_recommends: no
    state: present

- name: Add official Docker GPG key (Ubuntu)
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add official Docker GPG key (Debian)
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  when: ansible_distribution == 'Debian'

- name: Add official Docker APT repository (Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: 'docker-official'
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Add official Docker APT repository (Debian)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: 'docker-official'
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Install docker-ce and docker-compose
  apt:
    pkg:
      - docker-ce
      - docker-compose
    update_cache: yes
    install_recommends: yes
    state: present

- name: Add users to the Docker group
  user:
    name: "{{ system_user }}"
    groups: docker
    append: yes
